# fly.toml app configuration file generated for economic-competition-wisp on 2025-01-15T22:03:06+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'economic-competition-wisp'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  internal_port = 6969
  protocol = 'tcp'
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

[[services.ports]]
  handlers = ['http', 'tls']
  port = 6969

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
